version: '3.9'

services:
  backend:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8002:8002"
    networks:
      - app-network

  frontend:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
